#pragma once

#define LEADER_TIMEOUT 500

#define COMBO_COUNT 1

#define TAPPING_TERM 200
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD_PER_KEY

#define MK_KINETIC_SPEED
#define MOUSE_DELAY 0
#define MOUSEKEY_INTERVAL 16
